<Document>
<Version> 21 </Version>
<JMadonnaVersion> 9.0.94 </JMadonnaVersion>
<Bounds> 0 0 846 427 </Bounds>
<NotesEditor>
<jeditorpane>
<size>12</size><family>Dialog</family>
</jeditorpane>
</NotesEditor>
<Flowchart>
<ModelInfo>
<Pos> 0 0 </Pos>
<Rect> 0 0 0 0 </Rect>
<Color> 255 255 255 </Color>

<PageEntry>
<Id> 1 </Id>
</PageEntry>
<Entries>
<ReservoirInfo>
<Pos> 447 179 </Pos>
<Formula>
0
</Formula>
<LimitEquation> true </LimitEquation>
<PageEntry>
<Id> 2 </Id>
<NameEntry> 3 </NameEntry>
</PageEntry>
</ReservoirInfo>
<TextInfo>
<Pos> 421 151 </Pos>
<FontName> Serif </FontName>
<FontSize> 12 </FontSize>
<FontStyle> 0 </FontStyle>
<ShowBackground> 0 </ShowBackground>
<String>
s
</String>
<PageEntry>
<Id> 3 </Id>
<ForegroundColor> 30 30 0 </ForegroundColor>
<BackgroundColor> 180 200 240 </BackgroundColor>
</PageEntry>
</TextInfo>
<ReservoirInfo>
<Pos> 286 172 </Pos>
<Formula>
15
</Formula>
<PageEntry>
<Id> 4 </Id>
<NameEntry> 5 </NameEntry>
</PageEntry>
</ReservoirInfo>
<TextInfo>
<Pos> 260 144 </Pos>
<FontName> Serif </FontName>
<FontSize> 12 </FontSize>
<FontStyle> 0 </FontStyle>
<ShowBackground> 0 </ShowBackground>
<String>
v
</String>
<PageEntry>
<Id> 5 </Id>
<ForegroundColor> 30 30 0 </ForegroundColor>
<BackgroundColor> 180 200 240 </BackgroundColor>
</PageEntry>
</TextInfo>
<CloudInfo>
<Pos> 162 173 </Pos>)
<PageEntry>
<Id> 6 </Id>
</PageEntry>
</CloudInfo>
<FlowInfo>
<Pos> 212 170 </Pos>
<Formula>
-9.81
</Formula>
<PageEntry>
<Id> 7 </Id>
<NameEntry> 8 </NameEntry>
</PageEntry>
</FlowInfo>
<TextInfo>
<Pos> 200 154 </Pos>
<FontName> Serif </FontName>
<FontSize> 12 </FontSize>
<FontStyle> 0 </FontStyle>
<ShowBackground> 0 </ShowBackground>
<String>
dv
</String>
<PageEntry>
<Id> 8 </Id>
<ForegroundColor> 30 30 0 </ForegroundColor>
<BackgroundColor> 180 200 240 </BackgroundColor>
</PageEntry>
</TextInfo>
<PipeInfo>
<PipeIds> 6 7 </PipeIds>
<Pipette>
0.5 0.5 false
</Pipette>
<PageEntry>
<Id> 9 </Id>
</PageEntry>
</PipeInfo>
<PipeInfo>
<PipeIds> 7 4 </PipeIds>
<Pipette>
0.5 0.5 true
</Pipette>
<PageEntry>
<Id> 10 </Id>
</PageEntry>
</PipeInfo>
<FlowInfo>
<Pos> 362 170 </Pos>
<Formula>
v
</Formula>
<PageEntry>
<Id> 11 </Id>
<NameEntry> 12 </NameEntry>
</PageEntry>
</FlowInfo>
<TextInfo>
<Pos> 350 154 </Pos>
<FontName> Serif </FontName>
<FontSize> 12 </FontSize>
<FontStyle> 0 </FontStyle>
<ShowBackground> 0 </ShowBackground>
<String>
ds
</String>
<PageEntry>
<Id> 12 </Id>
<ForegroundColor> 30 30 0 </ForegroundColor>
<BackgroundColor> 180 200 240 </BackgroundColor>
</PageEntry>
</TextInfo>
<PipeInfo>
<PipeIds> 4 11 </PipeIds>
<Pipette>
0.5 0.5 false
</Pipette>
<PageEntry>
<Id> 13 </Id>
</PageEntry>
</PipeInfo>
<PipeInfo>
<PipeIds> 11 2 </PipeIds>
<Pipette>
0.5 0.5 true
</Pipette>
<PageEntry>
<Id> 14 </Id>
</PageEntry>
</PipeInfo>
<ArcInfo>
<PageEntry>
<Id> 15 </Id>
</PageEntry>
<ArcIds> 4 11 </ArcIds>
<ArcCtrl> 333 228 363 78 </ArcCtrl>
<ArrowMode> 0 </ArrowMode>
</ArcInfo>
</Entries>
</ModelInfo>
</Flowchart>
<imethod> euler </imethod>
<Param> STOPTIME 3.0 </Param>
<Param> DT 0.1 </Param>
<jmadonna.ParameterPanel>
<DocPanel>
</DocPanel>
<ParamSets>
</ParamSets>
</jmadonna.ParameterPanel>
<jmadonna.MultiPanel>
<DocPanel>
</DocPanel>
<DividerPercent> 0.8721374045801527 </DividerPercent>
<Orientation> 1 </Orientation>
<idx> 0 </idx>
<TabSplitter>
<SelectedIndex> 2 </SelectedIndex>
<visualMadonna.GlobalsPanel>
<DocPanel>
</DocPanel>
<jeditorpane>
<size>12</size><family>Dialog</family>
</jeditorpane>
</visualMadonna.GlobalsPanel>

<visualMadonna.ModelPanel>
<DocPanel>
</DocPanel>
<ModelId> 1 </ModelId>
<Grid> false </Grid>
<Background> 255 255 255 </Background>
</visualMadonna.ModelPanel>

<graph.COutputFrame>
<DocPanel>
<Name>
Graph 1
</Name>
</DocPanel>

<TabSplitter>
<SelectedIndex> 0 </SelectedIndex>
<graph.COutputView>
<Name> Graph </Name>
<GraphToolBar>
<Grid> 1 </Grid>
</GraphToolBar>
<Plot>
<LineWidth> 1 </LineWidth>
</Plot>
<OV_XVAR>
<VI_SYMBOL> TIME </VI_SYMBOL>
</OV_XVAR>
<OV_YVARS>
<OV_YVAR_I>
<VI_SYMBOL> s </VI_SYMBOL>
<VI_SHOW> true </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> v </VI_SYMBOL>
<VI_SHOW> true </VI_SHOW>
<VI_Y2AXIS> true </VI_Y2AXIS>
</OV_YVAR_I>
</OV_YVARS>
<OV_TABLE> false </OV_TABLE>
<OV_FFT> false </OV_FFT>
<OV_COLORS> true </OV_COLORS>
<OV_STYLES> false </OV_STYLES>
<OV_OSCMODE> false </OV_OSCMODE>
<OV_LINES>true </OV_LINES>
<OV_POINTS>false </OV_POINTS>
<OV_GRID>true </OV_GRID>
<OV_DBTN> true </OV_DBTN>
<OV_LEGEND> false </OV_LEGEND>
<OV_PARAMS> false </OV_PARAMS>
<OV_READOUT> false </OV_READOUT>
<OV_INITCOND> false </OV_INITCOND>
<OV_RDOUTFXFY> 0.0 0.0 </OV_RDOUTFXFY>
<OV_ZSNORMAL>
</OV_ZSNORMAL>
<OV_ZSFFT>
<ZS_SIZE> 1 </ZS_SIZE>
<ZS_I>
<ZS_XLOG> true </ZS_XLOG>
<ZS_Y1LOG> false </ZS_Y1LOG>
<ZS_Y2LOG> false </ZS_Y2LOG>
</ZS_I>
</OV_ZSFFT>
<OV_ZSOSCMODE>
</OV_ZSOSCMODE>
<OV_X1LABELS>  TIME </OV_X1LABELS>
<OV_Y1LABELS>  s </OV_Y1LABELS>
<OV_Y2LABELS>  v </OV_Y2LABELS>
<OV_LEGENDXY> 0.30000001192092896 0.5 </OV_LEGENDXY>
<OV_PARAMSXY> 0.30000001192092896 0.5 </OV_PARAMSXY>
</graph.COutputView>
</TabSplitter>
</graph.COutputFrame>
</TabSplitter>
<idx> 1 </idx>
<TabSplitter>
<SelectedIndex> -1 </SelectedIndex>
</TabSplitter>
</jmadonna.MultiPanel>

<ChemicalReactionDialog>
<ShowRates> true </ShowRates>
<ShowConsts> true </ShowConsts>
<ShowInits> true </ShowInits>
<ShowDiffs> true </ShowDiffs>
</ChemicalReactionDialog>
</Document>
