<Document>
<Version> 21 </Version>
<JMadonnaVersion> 9.0.94 </JMadonnaVersion>
<Bounds> 0 0 1280 888 </Bounds>
<NotesEditor>
<jeditorpane>
<size>12</size><family>Dialog</family>
</jeditorpane>
</NotesEditor>
<Flowchart>
<ModelInfo>
<Pos> 0 0 </Pos>
<Rect> 0 0 0 0 </Rect>
<Color> 255 255 255 </Color>

<PageEntry>
<Id> 1 </Id>
</PageEntry>
<Entries>
<ReservoirInfo>
<Pos> 185 146 </Pos>
<Formula>
0
</Formula>
<PageEntry>
<Id> 2 </Id>
<NameEntry> 3 </NameEntry>
</PageEntry>
</ReservoirInfo>
<TextInfo>
<Pos> 159 118 </Pos>
<FontName> Serif </FontName>
<FontSize> 12 </FontSize>
<FontStyle> 0 </FontStyle>
<ShowBackground> 0 </ShowBackground>
<String>
R1
</String>
<PageEntry>
<Id> 3 </Id>
<ForegroundColor> 30 30 0 </ForegroundColor>
<BackgroundColor> 180 200 240 </BackgroundColor>
</PageEntry>
</TextInfo>
<ReservoirInfo>
<Pos> 454 85 </Pos>
<Formula>
1
</Formula>
<PageEntry>
<Id> 4 </Id>
<NameEntry> 5 </NameEntry>
</PageEntry>
</ReservoirInfo>
<TextInfo>
<Pos> 428 57 </Pos>
<FontName> Serif </FontName>
<FontSize> 12 </FontSize>
<FontStyle> 0 </FontStyle>
<ShowBackground> 0 </ShowBackground>
<String>
R2
</String>
<PageEntry>
<Id> 5 </Id>
<ForegroundColor> 30 30 0 </ForegroundColor>
<BackgroundColor> 180 200 240 </BackgroundColor>
</PageEntry>
</TextInfo>
<FlowInfo>
<Pos> 315 144 </Pos>
<Formula>
123
</Formula>
<PageEntry>
<Id> 6 </Id>
<NameEntry> 7 </NameEntry>
</PageEntry>
</FlowInfo>
<TextInfo>
<Pos> 303 128 </Pos>
<FontName> Serif </FontName>
<FontSize> 12 </FontSize>
<FontStyle> 0 </FontStyle>
<ShowBackground> 0 </ShowBackground>
<String>
J1
</String>
<PageEntry>
<Id> 7 </Id>
<ForegroundColor> 30 30 0 </ForegroundColor>
<BackgroundColor> 180 200 240 </BackgroundColor>
</PageEntry>
</TextInfo>
<PipeInfo>
<PipeIds> 2 6 </PipeIds>
<Pipette>
0.5 0.5 false
</Pipette>
<PageEntry>
<Id> 8 </Id>
</PageEntry>
</PipeInfo>
<PipeInfo>
<PipeIds> 6 4 </PipeIds>
<Pipette>
0.5 0.5 true
</Pipette>
<PageEntry>
<Id> 9 </Id>
</PageEntry>
</PipeInfo>
</Entries>
</ModelInfo>
</Flowchart>
<imethod> rk4 </imethod>
<jmadonna.ParameterPanel>
<DocPanel>
</DocPanel>
<ParamSets>
</ParamSets>
</jmadonna.ParameterPanel>
<jmadonna.MultiPanel>
<DocPanel>
</DocPanel>
<DividerPercent> 0.9895615866388309 </DividerPercent>
<Orientation> 1 </Orientation>
<idx> 0 </idx>
<TabSplitter>
<SelectedIndex> 1 </SelectedIndex>
<visualMadonna.GlobalsPanel>
<DocPanel>
</DocPanel>
<jeditorpane>
<size>12</size><family>Dialog</family>
</jeditorpane>
</visualMadonna.GlobalsPanel>

<visualMadonna.ModelPanel>
<DocPanel>
</DocPanel>
<ModelId> 1 </ModelId>
<Grid> false </Grid>
<Background> 255 255 255 </Background>
</visualMadonna.ModelPanel>

</TabSplitter>
<idx> 1 </idx>
<TabSplitter>
<SelectedIndex> -1 </SelectedIndex>
</TabSplitter>
</jmadonna.MultiPanel>

<ChemicalReactionDialog>
<ShowRates> true </ShowRates>
<ShowConsts> true </ShowConsts>
<ShowInits> true </ShowInits>
<ShowDiffs> true </ShowDiffs>
</ChemicalReactionDialog>
</Document>
