<Document>
<Version> 21 </Version>
<JMadonnaVersion> 9.0.94 </JMadonnaVersion>
<Bounds> 0 0 1280 888 </Bounds>
<NotesEditor>
<jeditorpane>
<size>12</size><family>Dialog</family>
</jeditorpane>
</NotesEditor>
<Flowchart>
<ModelInfo>
<Pos> 0 0 </Pos>
<Rect> 0 0 0 0 </Rect>
<Color> 255 255 255 </Color>

<Globals>
globale=12
globale2=78

</Globals>
<PageEntry>
<Id> 1 </Id>
</PageEntry>
<Entries>
</Entries>
</ModelInfo>
</Flowchart>
<imethod> rk4 </imethod>
<jmadonna.ParameterPanel>
<DocPanel>
</DocPanel>
<ParamSets>
</ParamSets>
</jmadonna.ParameterPanel>
<jmadonna.MultiPanel>
<DocPanel>
</DocPanel>
<DividerPercent> 0.9895615866388309 </DividerPercent>
<Orientation> 1 </Orientation>
<idx> 0 </idx>
<TabSplitter>
<SelectedIndex> 0 </SelectedIndex>
<visualMadonna.ModelPanel>
<DocPanel>
</DocPanel>
<ModelId> 1 </ModelId>
<Grid> false </Grid>
<Background> 255 255 255 </Background>
</visualMadonna.ModelPanel>

<visualMadonna.GlobalsPanel>
<DocPanel>
</DocPanel>
<jeditorpane>
<size>12</size><family>Dialog</family>globale=12
globale2=78
</jeditorpane>
</visualMadonna.GlobalsPanel>

</TabSplitter>
<idx> 1 </idx>
<TabSplitter>
<SelectedIndex> -1 </SelectedIndex>
</TabSplitter>
</jmadonna.MultiPanel>

<ChemicalReactionDialog>
<ShowRates> true </ShowRates>
<ShowConsts> true </ShowConsts>
<ShowInits> true </ShowInits>
<ShowDiffs> true </ShowDiffs>
</ChemicalReactionDialog>
</Document>
