<Document>
<Version> 21 </Version>
<JMadonnaVersion> 9.0.94 </JMadonnaVersion>
<Bounds> 0 0 1280 888 </Bounds>
<NotesEditor>
<jeditorpane>
<size>12</size><family>Dialog</family>
</jeditorpane>
</NotesEditor>
<Flowchart>
<ModelInfo>
<Pos> 0 0 </Pos>
<Rect> 0 0 0 0 </Rect>
<Color> 255 255 255 </Color>

<PageEntry>
<Id> 1 </Id>
</PageEntry>
<Entries>
<ConverterInfo>
<Pos> 229 126 </Pos>
<Formula>
12
</Formula>
<PageEntry>
<Id> 2 </Id>
<NameEntry> 3 </NameEntry>
</PageEntry>
</ConverterInfo>
<TextInfo>
<Pos> 208 101 </Pos>
<FontName> Serif </FontName>
<FontSize> 12 </FontSize>
<FontStyle> 0 </FontStyle>
<ShowBackground> 0 </ShowBackground>
<String>
F1
</String>
<PageEntry>
<Id> 3 </Id>
<ForegroundColor> 30 30 0 </ForegroundColor>
<BackgroundColor> 180 200 240 </BackgroundColor>
</PageEntry>
</TextInfo>
<ConverterInfo>
<Pos> 381 145 </Pos>
<Formula>
F1/3
</Formula>
<PageEntry>
<Id> 4 </Id>
<NameEntry> 5 </NameEntry>
</PageEntry>
</ConverterInfo>
<TextInfo>
<Pos> 360 120 </Pos>
<FontName> Serif </FontName>
<FontSize> 12 </FontSize>
<FontStyle> 0 </FontStyle>
<ShowBackground> 0 </ShowBackground>
<String>
F2
</String>
<PageEntry>
<Id> 5 </Id>
<ForegroundColor> 30 30 0 </ForegroundColor>
<BackgroundColor> 180 200 240 </BackgroundColor>
</PageEntry>
</TextInfo>
<ArcInfo>
<PageEntry>
<Id> 6 </Id>
</PageEntry>
<ArcIds> 2 4 </ArcIds>
<ArcCtrl> 241 127 241 127 </ArcCtrl>
<ArrowMode> 0 </ArrowMode>
</ArcInfo>
</Entries>
</ModelInfo>
</Flowchart>
<imethod> rk4 </imethod>
<jmadonna.ParameterPanel>
<DocPanel>
</DocPanel>
<ParamSets>
</ParamSets>
</jmadonna.ParameterPanel>
<jmadonna.MultiPanel>
<DocPanel>
</DocPanel>
<DividerPercent> 0.9895615866388309 </DividerPercent>
<Orientation> 1 </Orientation>
<idx> 0 </idx>
<TabSplitter>
<SelectedIndex> 1 </SelectedIndex>
<visualMadonna.GlobalsPanel>
<DocPanel>
</DocPanel>
<jeditorpane>
<size>12</size><family>Dialog</family>
</jeditorpane>
</visualMadonna.GlobalsPanel>

<visualMadonna.ModelPanel>
<DocPanel>
</DocPanel>
<ModelId> 1 </ModelId>
<Grid> false </Grid>
<Background> 255 255 255 </Background>
</visualMadonna.ModelPanel>

</TabSplitter>
<idx> 1 </idx>
<TabSplitter>
<SelectedIndex> -1 </SelectedIndex>
</TabSplitter>
</jmadonna.MultiPanel>

<ChemicalReactionDialog>
<ShowRates> true </ShowRates>
<ShowConsts> true </ShowConsts>
<ShowInits> true </ShowInits>
<ShowDiffs> true </ShowDiffs>
</ChemicalReactionDialog>
</Document>
